name: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    needs: create-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build linux
        env:
        run: |
          make
          cat now.txt
